### ISSUE TITLE
读取返回的XML乱码

### ISSUE THREAD

**Issue by zhangchunyu2016** [shaojiankui/iOS-UDID-Safari#11]
`const received = (request, response) => {
    console.log(request.headers);
    console.log('------\n');

    let buffers = [];
    let nread = 0;
    request.on("data", (chunk) => {
        buffers.push(chunk);
        nread += chunk.length;
    });

    request.on("end", () => {
        let buffer = Buffer.concat(buffers, nread);

        console.log(buffer);
        console.log('\n');
        console.log(buffer.toString());

        response.writeHead(200, {"Content-Type": "text/plain; charset=utf-8"});
        response.end();
    })
}`

node实现，安装配置文件后回调，但是 buffer.toString() ，有很多字符是乱码

**Comment by appleudid** [comment]
内容已经签名了 你没解析 肯定有乱码部分

**Comment by appleudid** [comment]
@zhangchunyu2016

**Comment by zhangchunyu2016** [comment]
enen

**Comment by anhtai9710** [comment]
> `const received = (request, response) => { console.log(request.headers); console.log('------\n');
> 
> ```
> let buffers = [];
> let nread = 0;
> request.on("data", (chunk) => {
>     buffers.push(chunk);
>     nread += chunk.length;
> });
> 
> request.on("end", () => {
>     let buffer = Buffer.concat(buffers, nread);
> 
>     console.log(buffer);
>     console.log('\n');
>     console.log(buffer.toString());
> 
>     response.writeHead(200, {"Content-Type": "text/plain; charset=utf-8"});
>     response.end();
> })
> ```
> 
> }`
> 
> node实现，安装配置文件后回调，但是 buffer.toString() ，有很多字符是乱码

**Comment by anhtai9710** [comment]
Ggggg
