### ISSUE TITLE
get raw failed in ios 11.1.2

### ISSUE THREAD

**Issue by popking5466** [shaojiankui/iOS-UDID-Safari#4]
Printing description of raw:
POST /receive.do HTTP/1.1
Host: localhost:55555
Content-Type: application/pkcs7-signature
Connection: keep-alive
Accept: */*
User-Agent: Profile/1.0
Content-Length: 3501
Accept-Language: zh-cn
Accept-Encoding: gzip, deflate

NSString *plistString = [raw substringWithRange:NSMakeRange([raw rangeOfString:@"<?xml"].location, [raw rangeOfString:@"</plist>"].location + [raw rangeOfString:@"</plist>"].length)];

nsstring raw not have something like @"<?xml" or @"</plist>" or @"</plist>"  

what shall i do then ?

thx

**Comment by yangfangkuo** [comment]
这个应该不仅仅是在11.2系统上  而是应该是本地起了多个local server,然后返回的时候  返回的server不对了,预计是这个问题

**Comment by yangfangkuo** [comment]
好像还有一种可能,这个获取到的data没有读取结束就返回了,好像是这个,我看了下成功的时候的信息和这个的区别

**Comment by shaojiankui** [comment]
localhost 改成127.0.0.1就行了

**Comment by BossKing** [comment]
下载你最新版的还是会出现获取异常的现象 iPhone 6s Plus(iOS 12.1.2)

**Comment by BossKing** [comment]
用的是 iOS-UDID-Safari-LocalServer文件夹为使用iOS内置服务器作为服务端获取UDID

**Comment by BossKing** [comment]
老铁么 iOS内置服务器作为服务端获取UDID 可以参考哈这个 https://github.com/Magic-Unique/MUMobileGestalt
