### ISSUE TITLE
Not working on iOS 12

### ISSUE THREAD

**Issue by pwlkania** [shaojiankui/iOS-UDID-Safari#5]
It's not working on iOS 12. It seems to be a problem with ATS (App Transport Security settings). Added flag 'allows arbitrary loads' on true, but it didn't help.

**Comment by shaojiankui** [comment]
profile use https url

**Comment by shaojiankui** [comment]
profile use https url

**Comment by shaojiankui** [comment]
profile use https url

**Comment by shaojiankui** [comment]
profile use https url

**Comment by shaojiankui** [comment]
profile use https url

**Comment by shaojiankui** [comment]
profile use https url

**Comment by pwlkania** [comment]
Didn't help, getting error 

> An ssl error has occurred and a secure connection to the server cannot be made.

 (ATS flag in plist is still there)

**Comment by zhujieshan** [comment]
@pwlkania How did you solve it?

**Comment by zhujieshan** [comment]
原来是服务器配置的证书不对，苹果要求是TLS1.2，服务端配置是TLS1.0

**Comment by pwlkania** [comment]
Not really. I used this https://github.com/hunk/get-UDID

However on iOS 12 additionally you have to sign the _.mobileconfig_ file. I achieved it by using one of my valid distribution cert from apple developer account. 
You can check available certs by entering this command in terminal:

> /usr/bin/security find-identity -p codesigning -v

and later sing the _device.mobileconfig_ file

> /usr/bin/security cms -S -N "Mac Developer Application" -i /path/to/your.mobileconfig -o /path/to/your/signed/output.mobileconfig

(ref.: https://osxdominion.wordpress.com/2015/04/21/signing-mobileconfig-profiles-with-keychain-certificates/)

once you done it, use signed _device.mobileconfig_ instead of the old one. 

One more thing, if you want to use your own server (by changing URL in _device.mobileconfig_) make sure you have valid ssl certificate (looks like self-signed is not an option).

Good luck & have fun maybe you will figure out how to fix this repo

**Comment by lizhaojie001** [comment]
> 原来是服务器配置的证书不对，苹果要求是TLS1.2，服务端配置是TLS1.0

是服务器配置的证书不对吗,但是我们要是本地的话是不是有问题

**Comment by shaojiankui** [comment]
https证书不是必须的，后端的重定向如果不正确也会提示ats错误。重定向一定要使用301重定向,有些重定向默认是302重定向,
response.setStatus(301); //301之后iOS设备会自动打开safari浏览器
response.setHeader("Location", "http://192.168.1.106:8080/udid.jsp?UDID="+udid);
