### ISSUE TITLE
描述文件安装失败，无法与服务器建立连接。

### ISSUE THREAD

**Issue by small-Teenager** [shaojiankui/iOS-UDID-Safari#7]
如题，接收数据的接口地址地址可以直接访问。不太清除这里指的与服务器的连接是苹果服务器的连接还是自己接收地址的连接。

**Comment by small-Teenager** [comment]
java版

**Comment by shaojiankui** [comment]
苹果是不会出问题的，重定向确保要是301， ios12以后要https

**Comment by small-Teenager** [comment]
可以接收数据 UDIDAction.java 里面怎么出来UDID的，一直解析不出来

**Comment by small-Teenager** [comment]
已解决

**Comment by SiZapPaaiGwat** [comment]
> 已解决

怎么解决的，我也碰到这个问题了。
@small-Teenager

**Comment by small-Teenager** [comment]
用https协议接收udid，确保可以接收到数据就可以了

**Comment by SiZapPaaiGwat** [comment]
> 用https协议接收udid，确保可以接收到数据就可以了

我用的是 https 连接，服务端没有日志，😓

**Comment by small-Teenager** [comment]
> > 用https协议接收udid，确保可以接收到数据就可以了
> 
> 我用的是 https 连接，服务端没有日志，

你用https接收数据的url能够正常访问吗

**Comment by SiZapPaaiGwat** [comment]
> > > 用https协议接收udid，确保可以接收到数据就可以了
> > 
> > 
> > 我用的是 https 连接，服务端没有日志，
> 
> 你用https接收数据的url能够正常访问吗

现在可以了，请求头看到有数据，用 xml 解析不出来，估计类型不对？

```js
 'content-length': '3501',
 'content-type': 'application/pkcs7-signature'
 'user-agent': 'Profile/1.0'
```

**Comment by small-Teenager** [comment]
> > > > 用https协议接收udid，确保可以接收到数据就可以了
> > > 
> > > 
> > > 我用的是 https 连接，服务端没有日志，
> > 
> > 
> > 你用https接收数据的url能够正常访问吗
> 
> 现在可以了，请求头看到有数据，用 xml 解析不出来，估计类型不对？
> 
> ```js
>  'content-length': '3501',
>  'content-type': 'application/pkcs7-signature'
>  'user-agent': 'Profile/1.0'
> ```

听别人说是plist文件, 我是根据楼主的content字符串截取的

**Comment by SiZapPaaiGwat** [comment]
> > > > > 用https协议接收udid，确保可以接收到数据就可以了
> > > > 
> > > > 
> > > > 我用的是 https 连接，服务端没有日志，
> > > 
> > > 
> > > 你用https接收数据的url能够正常访问吗
> > 
> > 
> > 现在可以了，请求头看到有数据，用 xml 解析不出来，估计类型不对？
> > ```js
> >  'content-length': '3501',
> >  'content-type': 'application/pkcs7-signature'
> >  'user-agent': 'Profile/1.0'
> > ```
> 
> 听别人说是plist文件, 我是根据楼主的content字符串截取的

搞定了，这个是二进制文件，我以为是普通的 xml 文本。转换成字符串以后会有乱码，不过xml是完整的。

**Comment by chengte99** [comment]
> > > > > > 用https协议接收udid，确保可以接收到数据就可以了
> > > > > 
> > > > > 
> > > > > 我用的是 https 连接，服务端没有日志，
> > > > 
> > > > 
> > > > 你用https接收数据的url能够正常访问吗
> > > 
> > > 
> > > 现在可以了，请求头看到有数据，用 xml 解析不出来，估计类型不对？
> > > ```js
> > >  'content-length': '3501',
> > >  'content-type': 'application/pkcs7-signature'
> > >  'user-agent': 'Profile/1.0'
> > > ```
> > 
> > 
> > 听别人说是plist文件, 我是根据楼主的content字符串截取的
> 
> 搞定了，这个是二进制文件，我以为是普通的 xml 文本。转换成字符串以后会有乱码，不过xml是完整的。

请问一下，您是怎么收到数据的？我描述文件安装后服务端只收到 {}，apple不是post xml文本吗
@simongfxu

**Comment by SiZapPaaiGwat** [comment]
> > > > > > > 用https协议接收udid，确保可以接收到数据就可以了
> > > > > > 
> > > > > > 
> > > > > > 我用的是 https 连接，服务端没有日志，
> > > > > 
> > > > > 
> > > > > 你用https接收数据的url能够正常访问吗
> > > > 
> > > > 
> > > > 现在可以了，请求头看到有数据，用 xml 解析不出来，估计类型不对？
> > > > ```js
> > > >  'content-length': '3501',
> > > >  'content-type': 'application/pkcs7-signature'
> > > >  'user-agent': 'Profile/1.0'
> > > > ```
> > > 
> > > 
> > > 听别人说是plist文件, 我是根据楼主的content字符串截取的
> > 
> > 
> > 搞定了，这个是二进制文件，我以为是普通的 xml 文本。转换成字符串以后会有乱码，不过xml是完整的。
> 
> 请问一下，您是怎么收到数据的？我描述文件安装后服务端只收到 {}，apple不是post xml文本吗
> @simongfxu

看我的 gist：https://gist.github.com/simongfxu/8d7fff987db936ce6da0342930b6835d

**Comment by chengte99** [comment]
> > > > > > > > 用https协议接收udid，确保可以接收到数据就可以了
> > > > > > > 
> > > > > > > 
> > > > > > > 我用的是 https 连接，服务端没有日志，
> > > > > > 
> > > > > > 
> > > > > > 你用https接收数据的url能够正常访问吗
> > > > > 
> > > > > 
> > > > > 现在可以了，请求头看到有数据，用 xml 解析不出来，估计类型不对？
> > > > > ```js
> > > > >  'content-length': '3501',
> > > > >  'content-type': 'application/pkcs7-signature'
> > > > >  'user-agent': 'Profile/1.0'
> > > > > ```
> > > > 
> > > > 
> > > > 听别人说是plist文件, 我是根据楼主的content字符串截取的
> > > 
> > > 
> > > 搞定了，这个是二进制文件，我以为是普通的 xml 文本。转换成字符串以后会有乱码，不过xml是完整的。
> > 
> > 
> > 请问一下，您是怎么收到数据的？我描述文件安装后服务端只收到 {}，apple不是post xml文本吗
> > @simongfxu
> 
> 看我的 gist：https://gist.github.com/simongfxu/8d7fff987db936ce6da0342930b6835d

感谢，可以顺便问你个问题吗？
我服务端收到资料后 res.redirect(301, "网址");，但从手机上点击左上回到设定，却还显示安装文件哪边没设定好吗？
![螢幕快照 2019-08-29 下午3 09 48](https://user-images.githubusercontent.com/28803537/63918451-4fc4f800-ca6f-11e9-8c69-555902c369f4.png)

**Comment by chengte99** [comment]
> > > > > > > > 用https协议接收udid，确保可以接收到数据就可以了
> > > > > > > 
> > > > > > > 
> > > > > > > 我用的是 https 连接，服务端没有日志，
> > > > > > 
> > > > > > 
> > > > > > 你用https接收数据的url能够正常访问吗
> > > > > 
> > > > > 
> > > > > 现在可以了，请求头看到有数据，用 xml 解析不出来，估计类型不对？
> > > > > ```js
> > > > >  'content-length': '3501',
> > > > >  'content-type': 'application/pkcs7-signature'
> > > > >  'user-agent': 'Profile/1.0'
> > > > > ```
> > > > 
> > > > 
> > > > 听别人说是plist文件, 我是根据楼主的content字符串截取的
> > > 
> > > 
> > > 搞定了，这个是二进制文件，我以为是普通的 xml 文本。转换成字符串以后会有乱码，不过xml是完整的。
> > 
> > 
> > 请问一下，您是怎么收到数据的？我描述文件安装后服务端只收到 {}，apple不是post xml文本吗
> > @simongfxu
> 
> 看我的 gist：https://gist.github.com/simongfxu/8d7fff987db936ce6da0342930b6835d

感谢，已成功接收数续
@simongfxu 
请问能交流一下其他问题吗 qq 1786650931
